### ISSUE TITLE
Disabling Page Cache

### ISSUE THREAD

**Issue by mikeymike** [livechat/magento-livechat#1]
Looking into this module it seems odd that the approach was taken to require the disabling of Page Cache to function. Of course Page Cache is a pretty critical feature from a performance and scalability perspective so disabling it in most cases is not really an option (especially for large / heavy traffic sites). 

Is there any reason why this isn't done using the Knockout js templates ? That way there would be no need to disable page cache

**Comment by arioch1984** [comment]
Hi!
Any news on this problem?
If there is no solution we have to use another service for our customers :(

**Comment by MichalPaszowski** [comment]
We have fixed this issue - sorry to keep you waiting.
