### ISSUE TITLE
Compatibility with 2.3

### ISSUE THREAD

**Issue by heldchen** [livechat/magento-livechat#18]
the current 2.1.3 version on magento's marketplace is not installable through composer in 2.3.0-beta32, but a manual install still works perfectly fine. could you please update your `composer.json`?

**Comment by lexiconnect** [comment]
Also waiting for this fix to be able to upgrade to Magento 2.3

**Comment by SamB-GB** [comment]
Also awaiting for this to be fixed for 2.3...

 Problem 1
    - magento/framework 100.1.15 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.14 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.13 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.12 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.11 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.10 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.1 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.1.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.20 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.19 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.18 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.17 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.16 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.15 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.14 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.13 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.12 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.11 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.10 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.9 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.8 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.7 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.6 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.5 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.4 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.3 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - magento/framework 100.0.2 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.26) does not satisfy that requirement.
    - Conclusion: don't install magento/framework 100.1.16
    - Installation request for livechat/module-magento-livechat dev-master -> satisfiable by livechat/module-magento-livechat[dev-master].
    - Conclusion: don't install magento/framework 101.0.0|install magento/framework 100.1.16
    - livechat/module-magento-livechat dev-master requires magento/framework 100.*|101.0.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 101.0.0, 100.0.19, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.0.20, 100.1.12, 101.0.3, 100.1.13, 101.0.4, 101.0.5, 100.1.14, 100.1.15, 101.0.6, 100.1.16, 101.0.7].
    - magento/framework 101.0.1 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.2 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.3 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.4 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.5 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.6 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.7 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - Conclusion: don't install colinmollenhour/php-redis-session-abstract v1.3.4|install magento/framework 101.0.0|install magento/framework 100.1.16

**Comment by MichalPaszowski** [comment]
Hello everyone, first of all, sorry for late response. We have made the necessary changes and currently waiting for approval. If you want you can install the newest version via composer. Details can be found here:
https://www.livechatinc.com/kb/magento-livechat-integration/

**Comment by quarties** [comment]
I'll just add that we also use SemVer, so you don't have to use `dev-master`, details here: https://github.com/livechat/magento-livechat/issues/25
