### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by scottsb** [livechat/magento-livechat#25]
It would be great if this module used semantic versions (or any standard versioning structure for that matter). Current composer install instructions for the module indicate to require `dev-master`, which is considered poor practice since it can lead to unexpected breaking updates being installed.

**Comment by quarties** [comment]
Hi @scottsb, thanks for reaching us! I'm happy to announce that our module already uses SemVer and current version is [2.3.0](https://packagist.org/packages/livechat/module-magento-livechat#2.3.0). There's still pending Magento Marketplace technical review and we'll soon update our articles.

I'll keep this issue open for some time, so other developers could see that.

**Comment by scottsb** [comment]
Ah, OK. Good to know. The lack of any version history leading up to 2.3.0 made that unclear.
